// Send realistic-looking emails through Resend so the user can visually
// review attachments + inline images in their actual Gmail inbox.
//
// Run: pnpm --filter gmail-e2e-example send:real
// Optional filter: REAL_ONLY="pdf,photo" pnpm send:real

import { PDFDocument, StandardFonts, rgb } from "pdf-lib"

type Attachment = {
  readonly filename: string
  readonly content: string         // base64
  readonly content_type: string
  readonly content_id?: string
}

type RealFixture = {
  readonly name: string
  readonly subject: string
  readonly text?: string
  readonly html?: string
  readonly attachments?: ReadonlyArray<Attachment>
}

// ---------- generators ----------

const fetchPhoto = async (
  seed: string,
  w: number,
  h: number,
): Promise<Attachment> => {
  // picsum returns nice photographic JPEGs, deterministic per seed.
  const url = `https://picsum.photos/seed/${seed}/${w}/${h}.jpg`
  const r = await fetch(url, { redirect: "follow" })
  if (!r.ok) throw new Error(`picsum fetch ${url}: ${r.status} ${r.statusText}`)
  const buf = Buffer.from(await r.arrayBuffer())
  console.log(`[gen] photo ${seed} ${w}x${h} jpg = ${buf.length} bytes`)
  return {
    filename: `${seed}-${w}x${h}.jpeg`,
    content: buf.toString("base64"),
    content_type: "image/jpeg",
  }
}

const fetchPng = async (
  w: number,
  h: number,
  text: string,
): Promise<Attachment> => {
  // placehold.co supports explicit PNG output, useful for parser format coverage.
  const url = `https://placehold.co/${w}x${h}/4f46e5/ffffff/png?text=${encodeURIComponent(text)}`
  const r = await fetch(url, { redirect: "follow" })
  if (!r.ok) throw new Error(`placehold fetch ${url}: ${r.status} ${r.statusText}`)
  const buf = Buffer.from(await r.arrayBuffer())
  console.log(`[gen] png ${w}x${h} text="${text}" = ${buf.length} bytes`)
  return {
    filename: `placeholder-${w}x${h}.png`,
    content: buf.toString("base64"),
    content_type: "image/png",
  }
}

const generatePdf = async (): Promise<Attachment> => {
  const doc = await PDFDocument.create()
  doc.setTitle("Mail Station — Test PDF")
  doc.setAuthor("gmail-e2e-example")
  doc.setSubject("End-to-end test of attachment parsing")
  doc.setProducer("pdf-lib")

  const helv = await doc.embedFont(StandardFonts.Helvetica)
  const helvBold = await doc.embedFont(StandardFonts.HelveticaBold)
  const helvOblique = await doc.embedFont(StandardFonts.HelveticaOblique)

  // -- page 1
  const p1 = doc.addPage([612, 792])
  p1.drawText("Mail Station", { x: 50, y: 740, size: 36, font: helvBold, color: rgb(0.1, 0.2, 0.5) })
  p1.drawText("Test PDF Attachment", { x: 50, y: 710, size: 18, font: helvOblique, color: rgb(0.3, 0.3, 0.3) })
  p1.drawLine({ start: { x: 50, y: 695 }, end: { x: 562, y: 695 }, thickness: 1, color: rgb(0.7, 0.7, 0.7) })
  p1.drawText(`Generated: ${new Date().toISOString()}`, { x: 50, y: 670, size: 11, font: helv, color: rgb(0.4, 0.4, 0.4) })

  let y = 630
  const lh = 22
  const lines = [
    ["This PDF was generated by the gmail-e2e fixture sender to verify that:", helv],
    [" ", helv],
    ["  • PDF attachments are correctly parsed by the MIME walker", helv],
    ["  • filename, mime-type, and size are extracted from the Gmail payload", helv],
    ["  • the bytes round-trip end-to-end intact", helv],
    ["  • multi-page PDFs work fine — flip to page 2", helvBold],
    [" ", helv],
    ["The handler in main.ts only logs metadata, but the bytes are stored", helv],
    ["in Gmail and can be downloaded via gmailClient.attachmentGet() in", helv],
    ["consumer code.", helv],
  ] as const
  for (const [text, font] of lines) {
    p1.drawText(text, { x: 50, y, size: 13, font, color: rgb(0.1, 0.1, 0.1) })
    y -= lh
  }
  p1.drawText("Page 1 of 2", { x: 50, y: 50, size: 10, font: helv, color: rgb(0.6, 0.6, 0.6) })

  // -- page 2
  const p2 = doc.addPage([612, 792])
  p2.drawText("Page Two", { x: 50, y: 740, size: 36, font: helvBold, color: rgb(0.5, 0.1, 0.2) })
  p2.drawLine({ start: { x: 50, y: 720 }, end: { x: 562, y: 720 }, thickness: 1, color: rgb(0.7, 0.7, 0.7) })
  p2.drawText("If you can read this, multi-page PDF flow works.", { x: 50, y: 690, size: 14, font: helv })
  p2.drawText("Some test content:", { x: 50, y: 650, size: 14, font: helvBold })
  p2.drawText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do", { x: 50, y: 620, size: 12, font: helv })
  p2.drawText("eiusmod tempor incididunt ut labore et dolore magna aliqua.", { x: 50, y: 600, size: 12, font: helv })
  p2.drawRectangle({ x: 50, y: 450, width: 200, height: 100, color: rgb(0.1, 0.6, 0.4) })
  p2.drawText("a green rectangle", { x: 60, y: 490, size: 14, font: helvBold, color: rgb(1, 1, 1) })
  p2.drawText("Page 2 of 2", { x: 50, y: 50, size: 10, font: helv, color: rgb(0.6, 0.6, 0.6) })

  const bytes = Buffer.from(await doc.save())
  console.log(`[gen] pdf 2-page = ${bytes.length} bytes`)
  return {
    filename: "mail-station-test.pdf",
    content: bytes.toString("base64"),
    content_type: "application/pdf",
  }
}

const SVG_LOGO = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 80" width="240" height="80">
  <rect width="240" height="80" rx="8" fill="#1d4ed8"/>
  <text x="120" y="48" font-family="Helvetica, Arial, sans-serif" font-size="24" font-weight="700"
        fill="white" text-anchor="middle">mail-station</text>
</svg>`

const svgAttachment = (): Attachment => {
  const buf = Buffer.from(SVG_LOGO, "utf-8")
  console.log(`[gen] svg logo = ${buf.length} bytes`)
  return {
    filename: "mail-station-logo.svg",
    content: buf.toString("base64"),
    content_type: "image/svg+xml",
  }
}

// ---------- main ----------

const main = async () => {
  const apiKey = process.env.RESEND_API_KEY
  const from = process.env.RESEND_FROM
  const to = process.env.REGISTER_EMAIL
  if (!apiKey || !from || !to) {
    console.error("missing env: RESEND_API_KEY / RESEND_FROM / REGISTER_EMAIL")
    process.exit(1)
  }

  console.log("[real] generating attachments...")
  const photoLandscape = await fetchPhoto("mail-station-landscape", 800, 500)
  const photoPortrait = await fetchPhoto("mail-station-portrait", 500, 700)
  const pngPlaceholder = await fetchPng(600, 400, "mail-station PNG")
  const logoInlineSquare = await fetchPhoto("mail-station-logo-inline", 200, 60)
  const photoInlineHeader = await fetchPhoto("mail-station-header", 600, 200)
  const photoInlineFooter = await fetchPhoto("mail-station-footer", 400, 80)
  const pdf = await generatePdf()
  const svg = svgAttachment()

  const FIXTURES: ReadonlyArray<RealFixture> = [
    {
      name: "real-01-jpeg-photo",
      subject: "[real] JPEG photo attachment",
      text:
        "Here's a JPEG attachment for you to verify visually.\n\n" +
        "Open the email in Gmail, click the attachment — you should see a real photo.",
      attachments: [photoLandscape],
    },
    {
      name: "real-02-png-image",
      subject: "[real] PNG image attachment",
      text: "PNG-format attachment from placehold.co. Different mime, same path through the parser.",
      attachments: [pngPlaceholder],
    },
    {
      name: "real-03-pdf-2page",
      subject: "[real] 2-page PDF attachment",
      text:
        "Attached is a real 2-page PDF generated by pdf-lib. Open it and you should see\n" +
        "two pages with header text, body content, and a green rectangle on page two.",
      attachments: [pdf],
    },
    {
      name: "real-04-svg",
      subject: "[real] SVG attachment",
      text:
        "SVG is text-based. Most mail clients won't render it inline as an attachment\n" +
        "preview, but Gmail should let you download it. Open it in a browser to see\n" +
        "a small mail-station logo.",
      attachments: [svg],
    },
    {
      name: "real-05-inline-image",
      subject: "[real] inline image referenced via cid: (single)",
      html:
        "<div style=\"font-family: -apple-system, sans-serif; padding: 24px; max-width: 600px;\">" +
        "<p>This email has one inline image referenced from the HTML via " +
        "<code>cid:</code>. It should appear in the body, not as a separate attachment:</p>" +
        "<p><img src=\"cid:logo-inline\" alt=\"mail-station logo\" " +
        "style=\"max-width: 100%; border: 1px solid #eee; border-radius: 4px;\"></p>" +
        "<p>If the image renders inline above, the parser correctly preserved " +
        "<code>Content-ID: &lt;logo-inline&gt;</code> and <code>Content-Disposition: inline</code>.</p>" +
        "</div>",
      attachments: [{ ...logoInlineSquare, content_id: "logo-inline" }],
    },
    {
      name: "real-06-newsletter-multi-inline",
      subject: "[real] newsletter style — multiple inline images",
      html:
        "<div style=\"font-family: -apple-system, sans-serif; max-width: 640px; margin: 0 auto;\">" +
        "<img src=\"cid:hero-image\" alt=\"hero\" style=\"width: 100%; display: block;\">" +
        "<div style=\"padding: 24px;\">" +
        "<h1 style=\"margin: 0 0 12px; color: #111;\">Mail Station Test Newsletter</h1>" +
        "<p style=\"color: #444; line-height: 1.6;\">This is what a real marketing email " +
        "looks like — a hero image up top, body content, and a footer image at the bottom. " +
        "Both images are referenced from HTML via <code>cid:</code>.</p>" +
        "<p style=\"color: #444; line-height: 1.6;\">The parser should produce " +
        "<strong>two</strong> AttachmentRefs, both with <code>inline: true</code> and " +
        "their respective contentIds.</p>" +
        "</div>" +
        "<img src=\"cid:footer-image\" alt=\"footer\" style=\"width: 100%; display: block;\">" +
        "</div>",
      attachments: [
        { ...photoInlineHeader, content_id: "hero-image" },
        { ...photoInlineFooter, content_id: "footer-image" },
      ],
    },
    {
      name: "real-07-mixed-realistic",
      subject: "[real] realistic mixed: HTML + inline header + PDF attachment",
      text:
        "Hi,\n\nPlease find the attached test PDF.\n\nRegards,\nmail-station test suite",
      html:
        "<div style=\"font-family: -apple-system, sans-serif; max-width: 600px;\">" +
        "<img src=\"cid:realistic-header\" alt=\"header\" style=\"width: 100%; border-radius: 6px;\">" +
        "<h2 style=\"color: #111;\">Hi there,</h2>" +
        "<p style=\"color: #333; line-height: 1.6;\">Please find the attached test PDF. " +
        "It's a 2-page document generated by <code>pdf-lib</code>, and there's also a " +
        "header image embedded inline above.</p>" +
        "<p style=\"color: #333; line-height: 1.6;\">Regards,<br>mail-station test suite</p>" +
        "</div>",
      attachments: [
        { ...photoInlineHeader, content_id: "realistic-header" },
        pdf,
      ],
    },
    {
      name: "real-08-photo-and-pdf",
      subject: "[real] plain text + JPEG + PDF (two attachments)",
      text:
        "Two attachments on this one:\n" +
        "  - a portrait JPEG photo\n" +
        "  - a 2-page PDF\n" +
        "\nNo inline images, just plain text body with both as regular attachments.",
      attachments: [photoPortrait, pdf],
    },
  ]

  const only = process.env.REAL_ONLY
  const filters = only ? only.split(",").map((s) => s.trim()).filter(Boolean) : null
  const selected = filters
    ? FIXTURES.filter((f) => filters.some((q) => f.name.includes(q)))
    : FIXTURES

  if (selected.length === 0) {
    console.error(`no fixtures matched REAL_ONLY="${only}". available:`)
    for (const f of FIXTURES) console.error(`  - ${f.name}`)
    process.exit(1)
  }

  const DELAY_MS = 6000
  console.log(`\n[real] sending ${selected.length} via Resend → ${to}`)
  console.log(`[real] from: ${from}\n`)

  for (let i = 0; i < selected.length; i++) {
    const f = selected[i]!
    const body: Record<string, unknown> = {
      from,
      to: [to],
      subject: f.subject,
    }
    if (f.text) body.text = f.text
    if (f.html) body.html = f.html
    if (f.attachments) body.attachments = f.attachments

    const totalBytes = (f.attachments ?? []).reduce(
      (n, a) => n + Math.floor((a.content.length * 3) / 4),
      0,
    )

    try {
      const r = await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${apiKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify(body),
      })
      const txt = await r.text()
      if (!r.ok) throw new Error(`resend ${r.status}: ${txt}`)
      const out = JSON.parse(txt) as { id: string }
      console.log(
        `[send] ${f.name.padEnd(34)} attachments=${(f.attachments ?? []).length} ~${totalBytes}B  resend.id=${out.id}`,
      )
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e)
      console.error(`[send] ${f.name.padEnd(34)} FAILED: ${msg}`)
    }

    if (i < selected.length - 1) await new Promise((r) => setTimeout(r, DELAY_MS))
  }

  console.log("\n[real] done — check the inbox to visually review attachments")
}

main().catch((e) => {
  console.error("[fatal]", e)
  process.exit(1)
})
